# Setup
title: IFT6253 HW1
tagline: ""
description: ""
url: ""
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Zhiyang Xu
  url:
  email:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y

